/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

//We are using ADC1
//Analog input feeding through PC1 -pin9 (POT2)
//PC1 should be in Analog mode -MODER -11 for Analog mode
//PC6 LED used for ADC data comparison(Optional)
//ANG1 POT PC2 [10] ADC1 CH 12
//ANG2 POT PC1 [9] ADC1 CH 11
#include "stm32f405xx.h"
uint32_t  result;

int main (void) {

//PC2 ANALOG POT1
//PC1 ANALOG POT2
    /* set up pin PC6 for LED */

    RCC->AHB1ENR |=  (1<<2);	            /* enable GPIOC clock */
    GPIOC->MODER &= ~(3<<12);    /* clear pin mode for PC6 LED*/
    GPIOC->MODER |=  (1<<12);    /* set pin to output mode -01 set bit 12 */


    // set up pin PC1 for analog input
    //RCC->AHB1ENR |=  (1<<2);
    GPIOC->MODER &= ~(3<<2);    // clear pin mode PC1 -bit 3 and 2
    GPIOC->MODER |= (3<<2);    //set pin to ANALOG mode -11,setting bit 2 and 3

    /* setup ADC1 */
    RCC->APB2ENR |= (1<<8);     //Enable ADC1 clock -ADC1 is connected to APB2 Bus(84Mhz)
    ADC1->CR2 = 0;              //0: Disable ADC conversion and go to power down mode
    //The total number of conversions in the regular group must be written in the L[3:0] bits in the
   // ADC_SQR1 register
    //ADC regular sequence register 3
    ADC1->SQR1 &=~(0xF<<20); //Clearing bits 20-23, conversion sequence length is 1
    //SQR3 -its 4:0 SQ1[4:0]: 1st conversion in regular sequence
    ADC1->SQR3 |=(0xB<<0); //11   - conversion sequence and channel selection,Channel is 11 ADC1_CH11 for PC1
    //SQR1 is 0000: 1 conversion
    ADC1->CR1|=(1<<8);//Scan mode enable
    ADC1->CR1 |=0xB;   //01100  -Channel 11
    ADC1->CR2 |= 1;                 // Enable ADC2

    while (1) {
        ADC1->CR2 |= (1<<30);        /* start a conversion at regular channel*/
        while(!(ADC1->SR & 2)) {}       // wait for conv complete -monitor bit 1
        result = ADC1->DR;              /* read conversion result */
        if (result >100)

        	GPIOC->ODR &= ~( 1 << 6);//PC6 LED ON

        else

        GPIOC->ODR|= ( 1 << 6); //PC6 =1 // TURN OFF LED
    }
}


